-- イベント会場の緯度・経度・制限半径を追加
ALTER TABLE events ADD COLUMN latitude DOUBLE PRECISION;
ALTER TABLE events ADD COLUMN longitude DOUBLE PRECISION;
ALTER TABLE events ADD COLUMN radius_km DOUBLE PRECISION DEFAULT 1.0;
