ALTER TABLE events ADD COLUMN register_start TIMESTAMPTZ;
ALTER TABLE events ADD COLUMN register_end TIMESTAMPTZ;
ALTER TABLE events ADD COLUMN trade_start TIMESTAMPTZ;
ALTER TABLE events ADD COLUMN trade_end TIMESTAMPTZ;
