ALTER TABLE events ADD COLUMN latitude2 DOUBLE PRECISION;
ALTER TABLE events ADD COLUMN longitude2 DOUBLE PRECISION;
ALTER TABLE events ADD COLUMN radius_km2 DOUBLE PRECISION DEFAULT 1.0;
ALTER TABLE events ADD COLUMN latitude3 DOUBLE PRECISION;
ALTER TABLE events ADD COLUMN longitude3 DOUBLE PRECISION;
ALTER TABLE events ADD COLUMN radius_km3 DOUBLE PRECISION DEFAULT 1.0;
